name: CI_KanjiDome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend/
      
    - name: Build Taiko Solution
      run: dotnet build --no-restore
      working-directory: backend/
